### ISSUE TITLE
Not showing mean and scatter if either parameter is not converged

### ISSUE THREAD

**Issue by vvinuv** [Samreay/ChainConsumer#60] opened 2018-05-09 18:54 UTC
I used to give chains of parameters to ChainConsumer and get great results. It shows the mean and scatter in the above of all the triangle plots, if the parameters are converged. However, if there is a convergence problem in any of the parameters then the plot doesn't show the mean and scatter in the top of the plot. Do you have any resolution for this issue?

**Comment by Samreay** [comment] 2018-07-05 03:46
Sorry for the delay getting back to you Vinu, I took some technology free holidays! 

Would you be able to provide an example of this. What should be happening is if a parameter is not converged, only that parameter summary isnt shown, but the others should be!

**Comment by Samreay** [comment] 2019-09-04 05:53
Unable to reproduce, so closing this out unless we can get some more info.

**Closed by Samreay** 2019-09-04 05:53 UTC
