### ISSUE TITLE
Tick labels not being factored when plotting a subsample of parameters

### ISSUE THREAD

**Issue by Chris-Pedersen** [Samreay/ChainConsumer#83] opened 2020-10-28 23:08 UTC
Hi!

I'm hitting an unfortunate tick label issue in that a parameter with a very small numerical value isn't having the tick labels factored out when plotting a small subsample of parameters. In the first case it works fine:

![more_params](https://user-images.githubusercontent.com/16047009/97506000-dfb34a00-1971-11eb-9678-63c497cefe52.png)

However whenever I try and only plot a subset of parameters, the ticks for the parameter A_s are no longer being factored.

![less_params](https://user-images.githubusercontent.com/16047009/97506006-e215a400-1971-11eb-8a2f-169f8a870301.png)

I've tried playing around with the `configure` options, different max_ticks and font sizes, figure sizes etc, but none of this jigs the ticks into factoring. I also can't find a kwarg to pass anywhere. Do you have any suggestions? NB in the first case I'm still plotting a subsample of the parameters - there are 8 in the chain. It's only when I'm down to plotting 2 that this issue pops up.

Thanks very much!

**Comment by Samreay** [comment] 2020-10-28 23:51
Hey Chris! How odd, this isnt intended behaviour. Are you able to share the code snippet you used (and that data as well if possible) so that I can exactly reproduce (and fix) the issue?

**Comment by Chris-Pedersen** [comment] 2020-10-28 23:53
Hi Sam, sure I'll upload a reproducible example tomorrow, thanks a lot for looking at this!

**Comment by Chris-Pedersen** [comment] 2020-10-29 12:26
I've uploaded a zip file with a small subsample of the data and a notebook that creates two plots - one with the issue and one without. Thanks!

[cc_debug.zip](https://github.com/Samreay/ChainConsumer/files/5458275/cc_debug.zip)

**Comment by Samreay** [comment] 2020-10-30 01:19
What a weird issue! So it turns out that the current version of matplotlib should only have a single formatter per axis (https://github.com/matplotlib/matplotlib/issues/15376) and the PR to support multiple axes hasnt been merged (https://github.com/matplotlib/matplotlib/pull/13482). Fixing the issue by creating new x and y formatters for ever axis, and the fix should be in v0.32.0

**Closed by Samreay** 2020-10-30 01:19 UTC

**Comment by Samreay** [comment] 2020-10-30 04:38
v0.32.0 is now live, please let me know if this doesn't fix the issue for you :)

**Comment by Chris-Pedersen** [comment] 2020-10-30 20:07
Working for me, thanks a lot!
