### ISSUE TITLE
error in plotter.plot

### ISSUE THREAD

**Issue by steven-murray** [Samreay/ChainConsumer#42] opened 2017-12-05 02:15 UTC
Hi Sam, any ideas why I'd get the following matplotlib error all of a sudden?:

```
/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/text.pyc in draw(self, renderer)
    761             posy = float(textobj.convert_yunits(textobj._y))
    762             if not np.isfinite(posx) or not np.isfinite(posy):
--> 763                 raise ValueError("posx and posy should be finite values")
    764             posx, posy = trans.transform_point((posx, posy))
    765             canvasw, canvash = renderer.get_canvas_width_height()

ValueError: posx and posy should be finite values
```

I'm running the same code as I always have. May have upgraded versions of either matplotlib or chainconsumer since last time, I'm not sure. Current version of MPL: 2.1.0 and ChainConsumer: 0.23.1

**Comment by Samreay** [comment] 2017-12-05 05:47
Yeah, no idea! Are you able to reproduce it and send me code so I can try
as well?

**Comment by steven-murray** [comment] 2017-12-05 06:01
Yup:

```
xx = np.random.normal(size=(1000,2))
c = ChainConsumer()
c.add_chain(xx,
            parameters=['a','b'])
c.plotter.plot();
```

**Comment by Samreay** [comment] 2017-12-05 06:04
Alright I'll load up those versions of matplotlib and cc when I'm off the
bus and have a look. In case I can't reproduce, do you have the full stack
trace? What line from cc triggers the failure?

**Comment by steven-murray** [comment] 2017-12-05 06:43
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    332                 pass
    333             else:
--> 334                 return printer(obj)
    335             # Finally look for special method names
    336             method = get_real_method(obj, self.print_method)

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in <lambda>(fig)
    238 
    239     if 'png' in formats:
--> 240         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    241     if 'retina' in formats or 'png2x' in formats:
    242         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in print_figure(fig, fmt, bbox_inches, **kwargs)
    122 
    123     bytes_io = BytesIO()
--> 124     fig.canvas.print_figure(bytes_io, **kw)
    125     data = bytes_io.getvalue()
    126     if fmt == 'svg':

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2257                 orientation=orientation,
   2258                 bbox_inches_restore=_bbox_inches_restore,
-> 2259                 **kwargs)
   2260         finally:
   2261             if bbox_inches and restore_bbox:

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in print_png(self, filename_or_obj, *args, **kwargs)
    505 
    506     def print_png(self, filename_or_obj, *args, **kwargs):
--> 507         FigureCanvasAgg.draw(self)
    508         renderer = self.get_renderer()
    509         original_dpi = renderer.dpi

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in draw(self)
    428             if toolbar:
    429                 toolbar.set_cursor(cursors.WAIT)
--> 430             self.figure.draw(self.renderer)
    431         finally:
    432             if toolbar:

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1293 
   1294             mimage._draw_list_compositing_images(
-> 1295                 renderer, self, artists, self.suppressComposite)
   1296 
   1297             renderer.close_group('figure')

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/image.pyc in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in draw(self, renderer, inframe)
   2397             renderer.stop_rasterizing()
   2398 
-> 2399         mimage._draw_list_compositing_images(renderer, self, artists)
   2400 
   2401         renderer.close_group('axes')

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/image.pyc in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/axis.pyc in draw(self, renderer, *args, **kwargs)
   1145         self._update_label_position(ticklabelBoxes, ticklabelBoxes2)
   1146 
-> 1147         self.label.draw(renderer)
   1148 
   1149         self._update_offset_text_position(ticklabelBoxes, ticklabelBoxes2)

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/home/steven/miniconda3/envs/HIHOD/lib/python2.7/site-packages/matplotlib/text.pyc in draw(self, renderer)
    761             posy = float(textobj.convert_yunits(textobj._y))
    762             if not np.isfinite(posx) or not np.isfinite(posy):
--> 763                 raise ValueError("posx and posy should be finite values")
    764             posx, posy = trans.transform_point((posx, posy))
    765             canvasw, canvash = renderer.get_canvas_width_height()

ValueError: posx and posy should be finite values

<matplotlib.figure.Figure at 0x7f8c7649a150>
```

**Comment by steven-murray** [comment] 2017-12-05 06:44
hmmmm, I wonder if it's only in IPython...

**Comment by Samreay** [comment] 2017-12-05 07:34
Yeah I cant even find cc in the stack trace. Can you humor me and just try
a generic plot not using cc and confirm that it works?

**Comment by steven-murray** [comment] 2017-12-05 07:36
yeah, 

```
plt.plot(xx[:,0])
plt.text(0,4,'hey')
```
 works fine

**Comment by steven-murray** [comment] 2017-12-05 07:40
hmmm can confirm that running the small snippet above just in a python script then saving to pdf file works fine.

So it's not ChainConsumer's fault it would seem

**Comment by steven-murray** [comment] 2017-12-05 07:42
hmmm, also works fine in IPython. Might just be Jupyter...

**Comment by Samreay** [comment] 2017-12-05 07:43
Oh so something does fall over in ipython even without cc? If so, I'm
relieved, no idea how to debug a stack trace which doesn't reference cc
haha! If I've misunderstood I'll respond once I've touched down again!

**Comment by steven-murray** [comment] 2017-12-05 07:46
not quite. So cc works fine in a script, or in IPython, or even in Jupyter if I don't try to display the figure (i.e. if I just save it). However, when trying to display it, it chokes. However, if I just make a normal matplotlib plot in Jupyter, it shows fine. So it could be something to do with cc still.

**Comment by Samreay** [comment] 2017-12-05 11:22
Hmm, interesting! I'll try and reproduce tomorrow after the workshop.

**Comment by ColasRi** [comment] 2017-12-11 22:58
I run into the same issue then trying to run the first example from https://samreay.github.io/ChainConsumer/:
```
import numpy as np
from chainconsumer import ChainConsumer

mean = [0.0, 4.0]
data = np.random.multivariate_normal(mean, [[1.0, 0.7], [0.7, 1.5]], size=100000)

c = ChainConsumer()
c.add_chain(data, parameters=["$x_1$", "$x_2$"])
c.plotter.plot(filename="example.png", figsize="column", truth=mean)
```
`savefig` seems to be the issue. Replacing the last line by `c.plotter.plot(display=True, figsize="column", truth=mean)` works.
It looks like this open matplotlib issue: https://github.com/matplotlib/matplotlib/issues/6789.
Removing the `bbox_inches="tight"` from all `fig.savefig(f, bbox_inches="tight")` occurrences in plotter.py fixes the crash (but the labels are a bit messed up).
I am using python 2.7.10, matplotlib 2.1.0 and ChainConsumer 0.23.1 on up-to-date OSX.

**Comment by Samreay** [comment] 2017-12-11 23:04
Yeah, I found this last night too, when I updated matplotlib my figures stopped working with bbox_inches="tight".

Im debugging now trying to figure out if this is something that has broken in matplotlib 2.1.0 and how I should best work around it.

**Comment by Samreay** [comment] 2017-12-12 13:11
So funnily enough, right when I was about to release a new version which just said "Dont work with matplotlib 2.1.0", they released version 2.1.1. Which still doesnt have a complete fix. So the current workaround is just CC saying not to use the latest version of matplotlib, and I will remove the requirement when they fix the issue.

**Comment by Samreay** [comment] 2017-12-12 13:23
Please update CC and let me know if the issue persists. Ive simply made it roll back matplotlib version.

**Comment by ColasRi** [comment] 2017-12-12 14:40
That works for me, thanks.

**Comment by Samreay** [comment] 2017-12-12 21:44
Awesome. Closing issue out, thanks guys

**Closed by Samreay** 2017-12-12 21:44 UTC
